package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/hedwigai/cli/internal/defs"
)

const operationsTemplate = `// Code generated by tools/generate. DO NOT EDIT.

package generated

import "github.com/hedwigai/cli/internal/defs"

// BinaryName is the CLI binary name from config.
var BinaryName = {{ printf "%q" .BinaryName }}

// AuthEnvVar is the environment variable for the auth token.
var AuthEnvVar = {{ printf "%q" .AuthEnvVar }}

// SpecGroups contains all operations derived from OpenAPI specs.
var SpecGroups = []defs.SpecGroup{
{{- range .Groups }}
	{
		Name:           {{ printf "%q" .Name }},
		AuthMode:       {{ printf "%q" .AuthMode }},
		AuthHeader:     {{ printf "%q" .AuthHeader }},
		AuthPrefix:     {{ printf "%q" .AuthPrefix }},
		AuthQueryParam: {{ printf "%q" .AuthQueryParam }},
		Operations: []defs.Operation{
{{- range .Operations }}
			{
				Tag:         {{ printf "%q" .Tag }},
				OperationID: {{ printf "%q" .OperationID }},
				Summary:     {{ printf "%q" .Summary }},
				Description: {{ printf "%q" .Description }},
				Method:      {{ printf "%q" .Method }},
				Path:        {{ printf "%q" .Path }},
				BaseURL:     {{ printf "%q" .BaseURL }},
				NoAuth:      {{ .NoAuth }},
				HasBody:     {{ .HasBody }},
				Parameters: []defs.Parameter{
{{- range .Parameters }}
					{
						Name:        {{ printf "%q" .Name }},
						In:          {{ printf "%q" .In }},
						Type:        {{ printf "%q" .Type }},
						Required:    {{ .Required }},
						Default:     {{ printf "%q" .Default }},
						Description: {{ printf "%q" .Description }},
						Enum:        {{ enumSlice .Enum }},
					},
{{- end }}
				},
				BodyFields: []defs.BodyField{
{{- range .BodyFields }}
					{
						Name:        {{ printf "%q" .Name }},
						Type:        {{ printf "%q" .Type }},
						Required:    {{ .Required }},
						Description: {{ printf "%q" .Description }},
					},
{{- end }}
				},
			},
{{- end }}
		},
	},
{{- end }}
}
`

// GenerateInput holds all data needed to produce the generated Go file.
type GenerateInput struct {
	Groups     []defs.SpecGroup
	AuthEnvVar string
	BinaryName string
}

// Generate writes the generated operations.go file to outputDir.
func Generate(input GenerateInput, outputDir string) error {
	funcMap := template.FuncMap{
		"enumSlice": func(enums []string) string {
			if len(enums) == 0 {
				return "nil"
			}
			parts := make([]string, len(enums))
			for i, e := range enums {
				parts[i] = fmt.Sprintf("%q", e)
			}
			return "[]string{" + strings.Join(parts, ", ") + "}"
		},
	}

	tmpl, err := template.New("operations").Funcs(funcMap).Parse(operationsTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outPath := filepath.Join(outputDir, "operations.go")
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, input); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}
