binary_name: hai-admin
version: 0.1.0

auth:
  env_var: HEDWIGAI_AUTH_TOKEN

specs:
  portal: "https://portal.hedwigai.com/api/openapi.json"
  googledrive: "https://kgraph.hedwigai.com/shared/googledrive/openapi.json"
