binary_name: hai-socialresearch
version: 0.1.0

auth:
  env_var: HEDWIGAI_AUTH_TOKEN

specs:
  x: "https://toolkit.hedwigai.com/x/openapi.json"
  spider: "https://toolkit.hedwigai.com/spider/openapi.json"
  instagram: "https://toolkit.hedwigai.com/instagram/openapi.json"
  linkedin: "https://toolkit.hedwigai.com/linkedin/openapi.json"
